/* This file is generated by zits. Do not edit manually */

export enum TaggingUnitEnum {
	PrivateTag = 'PrivateTag',
}

export enum TaggingLinkType {
	PublicEntry = 'PublicEntry',
	PrivateEntry = 'PrivateEntry',
	PublicTags = 'PublicTags',
	PrivateTags = 'PrivateTags',
}
