/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "tagging" */
export const taggingFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"query_all_PrivateTag",
	"commit_private_tag",
	"tag_private_entry",
	"untag_private_entry",
	"find_private_tags_for_entry",
	"find_private_entries_with_tag",
	"probe_public_tags",
	"publish_public_tag",
	"tag_public_entry",
	"find_public_tags_for_entry",
	"find_public_entries_with_tag",
	"untag_public_entry",
];


/** Generate tuple array of function names with given zomeName */
export function generateTaggingZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of taggingFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zTagging" */
export const taggingZomeFunctions: [ZomeName, FunctionName][] = generateTaggingZomeFunctionsArray("zTagging");
