[package]
name = "delivery_integrity"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk.workspace = true
zome_delivery_integrity = {git = "https://github.com/ddd-mtl/delivery-zome", branch = "hdk-4.0" }
